services:
  app:
    build: .
    container_name: app
    ports:
      - "8000:8000"
    volumes:
      # Monta o diretório atual no diretório /app do contêiner.
      # Isso permite o live-reloading e a persistência do banco de dados SQLite.
      - .:/app
    # O comando abaixo sobrescreve o CMD do Dockerfile para habilitar o --reload,
    # que é ideal para o ambiente de desenvolvimento.
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload

